apiVersion: v1
kind: Pod
metadata:
  name: debugger-<nodeName>      # Please add the node name here to distinguish;
  labels:
    func: troubleshoot
    debug: node
spec:
  containers:
  - name: debugger
    image: mcr.microsoft.com/dotnet/runtime-deps:6.0      # This is the image used by the kubectl debug command in the MS Doc;
    stdin: true
    securityContext:
      privileged: true     # Enable Privileged permission;
    volumeMounts:
    - name: host-root-volume
      mountPath: /host
  volumes:
  - name: host-root-volume
    hostPath:
      path: /
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
  nodeName: <nodeName>     # Replace this part with the node name which you want to troubleshoot;
