apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 443
    command:
    - bash
    - -c
    - |
      apt update &>/dev/null
      apt install netcat-traditional -y
      while true; do nc -lp 443; done
