apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: ingress-appgw-helm-custom
rules:
- apiGroups: [""]
  resources: ["endpoints", "pods", "secrets", "namespaces", "services", "events", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["appgw.ingress.k8s.io", "networking.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses/status"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
